[package]
name = "rust-anim"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
crossterm = "0.28.1"
noise = "0.9.0"
rand = "0.8.5"
rand_pcg = "0.3.1"
ratatui = "0.29.0"

[profile.release]
debug = true