[package]
name = "mandelbrot-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.9"
pollster = "0.4.0"
bytemuck = { version = "1.14", features = ["derive"] }
futures = "0.3.32"
image = "0.25.9"
num-complex = "0.4.6"
nannou = "0.19.0"
tokio = "1.49.0"
nannou_egui = "0.19.0"
